### ISSUE TITLE
SEGI Cascaded crashing

### ISSUE THREAD

**Issue by Dunathan** [sonicether/SEGI#15]
No problems using SEGI on my camera, but when I use SEGI Cascaded, my screen goes black and after a short while Unity screen is all black. Windows notify that my video board stopped working and recovered from an issue, or something like it.

Happens instantly and all the time.

Reproduction:
On a clean project, add SEGI Cascaded to the camera.

Using SEGI:
SEGI.v0.9.0

My hardware is:
Core i7 Q740
NVIDIA GeForce GTX 460M
Windows 7
Unity 2017.1

**Comment by alexcallgtab** [comment]
Hi, I also had the problem on SEGI Cascaded. Screen freeze with result unity crash or graphics drivers crash.

GTX1080
SEGI.v0.9.0
unity 2017.1

I think the problem comes from the "Voxel AA" option trying to disable it.
I continue the tests but for the moment without the mode "Voxel AA" the drivers drivers did not plant for me.

**Comment by alexcallgtab** [comment]
Well this is not voxel mode AA
I check the infinity bounce

**Comment by nxrighthere** [comment]
It's a known issue.

[Intel HD 5500](https://forum.unity.com/threads/segi-fully-dynamic-global-illumination.410310/page-30#post-3226665)
[GeForce GT 555M](https://forum.unity.com/threads/segi-fully-dynamic-global-illumination.410310/page-30#post-3226476)
[GeForce GTX 980](https://forum.unity.com/threads/segi-fully-dynamic-global-illumination.410310/page-30#post-3228025)

**Comment by alexcallgtab** [comment]
I managed to reproduce the crash by making rotations of directional light.
the bug must be in the level of the GI update.

Module 1
C:\Program Files\Unity\Editor\OpenRL.dll
Image Base: 0x80000000  Image Size: 0x00c30000
File Size:  12654592    File Time:  2017-08-31_110228
Version:
   Company:    Imagination Technologies, Inc.
   Product:    OpenRL™
   FileDesc:   OpenRL™ Library
   FileVer:    1.5.100.0
   ProdVer:    1.5.100.0

Module 2
C:\Program Files\Unity\Editor\OpenRL_pthread.dll
Image Base: 0x80000000  Image Size: 0x0000f000
File Size:  42496       File Time:  2017-08-31_110228
Version:
   Company:    Open Source Software community LGPL
   Product:    POSIX Threads for Windows LPGL
   FileDesc:   MS C 32 bit
   FileVer:    2.9.0.0
   ProdVer:    2.9.0.0

**Comment by nxrighthere** [comment]
Thank you for the information, this issue should be [fixed](https://github.com/sonicether/SEGI/pull/17/files) now. Also, please don't use the cascaded version from the release, it has memory leaks that have been [fixed](https://github.com/sonicether/SEGI/pull/2/files) a while ago.
